ALTER TABLE "Experience" ADD COLUMN "workload" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Course" ADD COLUMN "workload" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Certification" ADD COLUMN "workload" TEXT NOT NULL DEFAULT '';
ALTER TABLE "JobAnalysis" ADD COLUMN "jobUrl" TEXT NOT NULL DEFAULT '';
