export const state = {
  user: null,
  billing: null,
  token: null,
  jobs: [],
  profile: null,
  profiles: [],
  activeProfileId: "",
  matchHistory: [],
  nextCursorMatchHistory: null,
  matchHistoryHasMore: false,
  sharedMatchedJobs: [],
  sharedMatchedJobsPeriod: "month",
  pendingApplicationAnalysis: null,
  lastMatchResult: null,
  resumeFiles: [],
  filters: {
    q: "",
    titulo: "",
    empresa: "",
    linkVaga: "",
    status: "",
    fase: "",
    subprofileId: "",
    origin: "",
    period: "month", // day | week | month | all | custom
    dateFrom: "",
    dateTo: "",
  },
};
