const router = require("express").Router();
const { authMiddleware } = require("../middlewares/auth");
const profileController = require("../controllers/profile.controller");

router.use(authMiddleware);

router.get("/profiles", profileController.listProfiles);
router.post("/profiles", profileController.createProfile);
router.delete("/profiles/:id", profileController.deleteProfile);
router.get("/profile", profileController.getProfile);
router.put("/profile", profileController.updateProfile);
router.put("/profile/skills", profileController.updateSkills);
router.put("/profile/subprofile-allocation", profileController.updateSubprofileAllocation);
router.post("/profile/projects", profileController.addProject);
router.put("/profile/projects/:id", profileController.updateProject);
router.delete("/profile/projects/:id", profileController.deleteProject);
router.post("/profile/experiences", profileController.addExperience);
router.put("/profile/experiences/:id", profileController.updateExperience);
router.delete("/profile/experiences/:id", profileController.deleteExperience);
router.post("/profile/courses", profileController.addCourse);
router.put("/profile/courses/:id", profileController.updateCourse);
router.delete("/profile/courses/:id", profileController.deleteCourse);
router.post("/profile/certifications", profileController.addCertification);
router.put("/profile/certifications/:id", profileController.updateCertification);
router.delete("/profile/certifications/:id", profileController.deleteCertification);
router.post("/profile/languages", profileController.addLanguage);
router.put("/profile/languages/:id", profileController.updateLanguage);
router.delete("/profile/languages/:id", profileController.deleteLanguage);
router.post("/profile/educations", profileController.addEducation);
router.put("/profile/educations/:id", profileController.updateEducation);
router.delete("/profile/educations/:id", profileController.deleteEducation);
router.post("/match", profileController.match);
router.get("/shared-matched-jobs", profileController.listSharedMatchedJobs);
router.get("/optimized-resumes", profileController.listOptimized);
router.get("/optimized-resumes/:id/download", profileController.downloadOptimized);
router.delete("/optimized-resumes/:id", profileController.deleteOptimized);
router.patch("/job-analyses/:id", profileController.updateAnalysis);
router.get("/job-analyses/:id", profileController.getAnalysis);
router.post("/job-analyses/:id/recalculate", profileController.recalculateAnalysis);
router.post("/job-analyses/:id/create-application", profileController.createApplication);

module.exports = router;
