ALTER TABLE "Project" ADD COLUMN "learnedSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Course" ADD COLUMN "learnedSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Certification" ADD COLUMN "learnedSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Education" ADD COLUMN "learnedSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
